name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
      - name: Run
        run: |
          python3 main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          HOLDER_LABEL: "holder-test"
          DELIMITER: "-"
      - uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.0.7
          branches: |
            [
              'v1.x'
            ]
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/git@9.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
